#!/bin/sh

rm -rf rom.o rom.bin rom.dbg rom.*.txt

ca65 tests.asm -g -o rom.o
ld65 -o rom.bin -C tests.cfg rom.o -m tests.map.txt -Ln tests.labels.txt --dbgfile tests.dbg

echo ""
echo ""
echo "Hex Dump"
echo "------------------------------------------------------------------------------"
hexdump -C rom.bin
echo "------------------------------------------------------------------------------"
echo ""