#!/bin/sh

rm -rf rom.o rom.bin rom.dbg rom.*.txt

ca65 AllSuiteA.asm -g -o suite.o
ld65 -o suite.bin -C tests.cfg suite.o -m tests.map.txt -Ln tests.labels.txt --dbgfile tests.dbg

echo ""
echo ""
echo "Hex Dump"
echo "------------------------------------------------------------------------------"
hexdump -C suite.bin
echo "------------------------------------------------------------------------------"
echo ""