#!/bin/sh

rm -rf suite.o suite.bin suite.dbg suite.*.txt

ca65 tests.asm -g -o rom.o
ld65 -o rom.bin -C tests.cfg rom.o -m suite.map.txt -Ln suite.labels.txt --dbgfile suite.dbg

echo ""
echo ""
echo "Hex Dump"
echo "------------------------------------------------------------------------------"
hexdump -C rom.bin
echo "------------------------------------------------------------------------------"
echo ""